spring:
  application:
    name: graphql-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

graphql:
  servlet:
    mapping: /demo/graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /demo/graphql
    subscriptions: /subscriptions
  subscriptions:
    reconnect: false
    timeout: 30
  enabled: true
  pageTitle: GraphiQL

server:
  port: 8099

orika:
  enabled: true
  useBuiltinConverters: true
  useAutoMapping: true
  mapNulls: false
  dumpStateOnException:  true
  favorExtension: true
  captureFieldContext: true
